title: 윤장이 블로그
description: 개인 스터디 및 내용 정리 블로그
theme: just-the-docs

url: https://joe-yoon-jang.github.io/io_docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template